config/routes.rb
Rails.application.routes.draw do
  #devise_for :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "users/dashboard"
  
  devise_scope :user do
  get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  root to: 'restaurants#index'

  resources :restaurants
  resources :reservations, :only => [:show, :new, :create, :destroy, :index], :controller => 'reservations'
  
  devise_for :users 

  resources :restaurants, :except => [:new, :create] do
    resources :reservations, :only => [:create]
  end

  resources :users do
    resources :restaurants, :only => [:new, :create]
  end

  resources :restaurants do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_and_belongs_to_many :restaurants
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :restaurant
	belongs_to :user
	
	validates_uniqueness_of :restaurant_id, scope: [:user_id]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	
	belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user

  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user
  
  has_many :reservations, dependent: :destroy
  accepts_nested_attributes_for :reservations
  has_and_belongs_to_many :categories 

  def reservation
  	@reservation = Reservation.new
  end

  def favorited_by?(user)
    favorited_by.include?(user)
  end

  def exists?(reservation)
    reservations.include?(reservation)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :email, presence: true, uniqueness: true
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create 

has_many :restaurants, :foreign_key => :owner_id
has_many :favorite_restaurants, through: :favorites, :source => :restaurant
has_many :favorites 
validates_presence_of :role

		def owner?
			role == "owner"
		end

		def admin?
			role == "admin"
		end

		def patron?
			role == "patron"
		end

def is_favorited?(restaurant)
  favorited_restaurants.include?(restaurant)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

 
def after_sign_in_path_for(resource)
  restaurants_path
end

 protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
   end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.where("name like ?", "%#{params[:q]}%")
		respond_to do |format|
			format.html
			format.json { render :json => @categories.map(&:attributes) }
		end
	end

	def show
		@category = Category.find(params[:id])
			@restaurants = @category.restaurants
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		begin
			@restaurant.favorited_by << current_user
			redirect_to @restaurant, :notice => 'You have successfully favorited this restaurant.'
		rescue ActiveRecord::RecordInvalid
			puts "Whoops"
		end
		@restaurants = Restaurant.all
	end

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
		@restaurant.favorited_by.delete(current_user)
		redirect_to @restaurant, :notice => 'You have successfully unfavorited this restaurant.'
		@restaurants = Restaurant.all
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :get_restaurant, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, :except => [:index, :show]

	def index
		@reservations = Reservation.all
	end

	def show
		@reservation = Reservation.find(params[:restaurant_id])
	end

	def create
		@reservation = Reservation.new(reservation_params)
		if @reservation.save
			ReservationMailer.reservation_notification(@reservation).deliver
			redirect_to reservations_path, :notice => 'You have successfully made a reservation.'
		else
			render 'restaurant/show', :notice => 'Something went wrong. Please try again.'
		end
	end

	def destroy
		@reservation.destroy

		resdirect to @reservation.restaurants
	end

	private
		def reservation_params
			params.require(:reservation).permit(:email, :datetime, :message, :restaurant_id)
		end


	protected

		def get_restaurant
			@restaurant = Restaurant.find(params[:restaurant_id])
		end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]

def index
	@restaurants = Restaurant.all
end

def new
	@restaurant = Restaurant.new
end

def create
	@restaurants = Restaurant.new(restaurant_params)
	@restaurants = current_user.restaurants.new(restaurant_params)
	if @restaurants.save
		flash[:success] = "Restaurant was created, bitch."
		redirect_to @restaurants
	else
		render 'new'
	end
end

def show
	@restaurant = Restaurant.find(params[:id])
	@reservations = Reservation.where(restaurant_id: params[:id])
end

def edit
	@restaurants = current_user.restaurants.find(params[:id])
end

def update
	@restaurant = current_user.restaurants.find(params[:id])
	if @restaurant.update(restaurant_params)
		flash[:success] = "Restaurant was updated, bitch."
		redirect_to @restaurant
	else
		render 'edit'
	end
end

def destroy
	@restaurant = Restaurant.find(params[:id])
	@restaurant.destroy
	if @restaurant.destroy
		flash[:danger] = "restaurant was deleted and stuff"
	else
		flash[:danger] = "restaurant was not deleted and stuff"
	end
	redirect_to restaurants_path
end

private

     # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:owner_id, :name, :content, :address)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def dashboard
		@user = current_user
		@restaurants = current_user.restaurants
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/favorites/create.js.erb
$("#restaurants").html("<%= escape_javascript(render("restaurants/list", restaurants: @restaurants)) %>")

app/views/favorites/destroy.js.erb
$("#restaurants").html("<%= escape_javascript(render("restaurants/list", restaurants: @restaurants)) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservester</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="navbar navbar-fixed-top">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email%></strong>
    <%= link_to 'Dashboard', users_dashboard_path, :class => 'navbar-link' %> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to 'Logout', logout_path, :class => 'navbar-link' %>
  <% else %>
    <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
  <% end %>
	<div class="navbar-inner">
		<div class="container">
			<a href="#" class="brand">Reservester</a>
			<ul class="nav">
				<li><%= link_to "All Restaurants", restaurants_path %></li>
			</ul>
		</div>
	</div>
</div>	
<% if notice %><p class="notice"><%= notice %></p><% end %>
<% if alert %><p class="alert"><%= alert %></p><% end %>

    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= simple_form_for :reservation, html: { class: 'form-horizontal' } do |f| %>
	<%= f.input :name %></br>
	<%= f.input :email %></br>
	<%= f.input :datetime %></br>
	<%= f.input :message %></br>
	<%= f.hidden_field :restaurant_id %></br>
	<%= f.button :submit %></br>
<% end %>

app/views/reservations/_reservation.html.erb
<li>
	<%= reservation.name %>
	<%= reservation.email %>
	<%= reservation.datetime %>
	<%= reservation.message %>
</li>

app/views/reservations/index.html.erb
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/_form.html.erb
<div class="modal-dialog">
 <div class="modal-content">
   <%= form_for @restaurant, remote: true, html: { style: "display:inline;" } do |f| %>
     <div class="modal-body">
       <ul class="errors"></ul>

       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name %>
       </div>

       <div class="form-group">
        <%= f.label :category %>
         <%= f.select(:categories) do %>
          <% Category.all.each do |c| %>
            <%= content_tag(:option, c.name) %>
            <% end %>
          <% end %>
       </div>

        <div class="form-group">
         <%= f.label :address %>
         <%= f.text_field :address %>
        </div>

        <div class="form-group">
         <%= f.label :content %>
         <%= f.text_area :content %>
       </div>

       <%= f.hidden_field :user_id, value: current_user.id %>

     <div class="modal-footer">
       <%= f.submit class: "btn btn-primary" %>
       <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
     </div>
     </div>
   <% end %>
 </div>
</div>

app/views/restaurants/_list.html.erb
<% if signed_in? %>
	<% restaurants.each do |restaurant| %>
	  <b><%= link_to restaurant.name, restaurant_path(restaurant) %></b>
	  <p><%= restaurant.address %></p> 
	  <p><%= restaurant.content %></p>

	  <% if signed_in? and current_user.patron? %>
	  	<% if restaurant.favorited_by?(current_user) %>
	    <%= link_to "unfavorite", restaurant_favorites_path(restaurant, type: "unfavorite"), method:  :delete, remote: true %>
	    <% else %>
	    <%= link_to "favorite", restaurant_favorites_path(restaurant, type: "favorite"), method: :post, remote: true %>
	    <% end %>
	  	</br>
	  <% end %>
	<% end %>
<% end %>

app/views/restaurants/_map.html.erb
<head>
	<meta name = "viewport" content="width=device-width, initial-scale 1.0">
	<link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.css" rel="stylesheet" media="screen">
	<script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
	<style>
		#map-container { height: 300px; }
	</style>
</head>

<body>
	<div id="map-container" class="col-md">
    <script> 
<iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyD5nt-kaFLNPJ4eifWEBOKyplZFE35MZ6E&q=<%= @restaurant.address %>">
</iframe>
  
    </script>
</div>

</body>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="page-header">
   <h1>Restaurants are cool, you should eat at them.</h1>
</div>

<div id="restaurants" class="restaurant">
  <%= render 'restaurants/list', restaurants: @restaurants %>
</div> 

<% if not signed_in? %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
	</br>
	<strong>Name:</strong>
	<%= @restaurant.name %></br> 
	<strong>Category:</strong>
	<%= @restaurant.categories.map{ |c| c.name }.join(", ") %></br>
	<strong>Description:</strong>
	<%= @restaurant.content %></br>
	<strong>Address:</strong>
	<%= @restaurant.address %></br>

<%= render 'map' %>

<% if signed_in? %>
	<h3>Reservations</h3>
<% end %>
  <ul>
	<%= render(@reservations) || "No reservations" %>
  </ul>
</br>

<%= render 'reservations/form' %>

<%= link_to 'Back', restaurants_path %>

app/views/users/dashboard.html.erb
<% if current_user.role == "owner" %>

<h1><%= current_user.email %>'s Dashboard</h1>
        <div>
            <%= link_to "Add New Restaurant", new_restaurant_path, class: "btn btn-success" %>
        </div>
        <div class="meta">
          <span class="admin">
            <table>
                <%- @restaurants.each do |restaurant| %>
                <tr>
                    <b><%= link_to restaurant.name, restaurant_path(restaurant) %></b>
                </br>
                  <%= link_to "Edit", edit_restaurant_path(restaurant) %>
                </br>    
                    |<%= link_to "Delete", restaurant, method: :delete, data: { confirm: "Are you sure you want to remove this restaurant from the directory?"} %>
                </tr>
              </br>
          </span>
       </div>
                <%- end %>
            </table>
<% end %>

<% if current_user.role == "patron" %>
    <h1><%= current_user.email %>'s Dashboard </h1>
    <div>
        <h2>Favorited Restaurants</h2>
    </div>
    

  <table class="table table-striped">
    <% current_user.favorite_restaurants.each do |restaurant| %>
       </br>
        </br>
          <b><%= restaurant.name %></b>
          <p><%= restaurant.address %></p> 
          <p><%= restaurant.content %></p> 
        <%= link_to "unfavorite", restaurant_favorites_path(restaurant, type: "unfavorite"), method: :put, :remote => true %>
        <% end %>
  </table>

<% end %>